### ISSUE TITLE
Typo in Installation Prerequisite

### ISSUE THREAD

**Issue by 0xapurv** [router-protocol/router-chain-docs#4]
## Summary of Bug
Typo In Installation Prerequisite Page. 
![image](https://user-images.githubusercontent.com/59207688/226576739-99c24a55-3e67-45b7-8555-451b9a8a1eb8.png)

It should be like this:
```
rustup target list --installed
# if wasm32 is not listed after running the aforementioned command, run the following:
rustup target add wasm32-unknown-unknown
```

## Steps to Reproduce
Visit <https://devnet-docs.routerprotocol.com/router-core/installing-prerequisites> and see under **Installing Rust on Windows 10** section.

**Comment by vatsalgupta13** [comment]
Resolved.
